function [fitresult, gof] = sumsines8Fit(time, hipFull,sinnum)
%CREATEFIT(TIME,HIPFULL)
%  Create a fit.
%
%  Data for 'sumSines8Fit' fit:
%      X Input : time
%      Y Output: hipFull
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Nov-2019 16:53:25


%% Fit: 'sumSines8Fit'.
[xData, yData] = prepareCurveData( time, hipFull );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
switch sinnum
    case 8
        % Set up fittype and options.
        ft = fittype( 'sin8' );
        opts.Lower = [0 0 -Inf 0 0 -Inf 0 0 -Inf 0 0 -Inf 0 0 -Inf 0 0 -Inf 0 0 -Inf 0 0 -Inf];
        opts.StartPoint = [42.6627724162217 0.315701784276956 3.11303228957304 32.6179187577667 1.89421070566174 -1.34691381395217 18.0935633487104 0.631403568553913 -1.62809157147457 5.77942365918501 3.78842141132348 1.32994520311686 3.59591183234497 1.26280713710783 -1.68783604739075 1.77571252712678 5.68263211698522 -0.275772850761761 0.971483805362579 7.57684282264696 1.02647476749177 0.898110245754916 2.52561427421565 -1.78350824288929];
    case 4
        ft = fittype( 'sin4' );
        opts.Lower = [0 0 -Inf 0 0 -Inf 0 0 -Inf -Inf 0 -Inf];
        opts.StartPoint = [48.8124726533666 1.89421070566174 -1.49316094087098 33.7179137329783 0.315701784276956 3.09967248290263 14.2924149805555 0.631403568553913 -1.65489163260383 5.13435200697129 3.78842141132348 1.1731817029952];
end
        % Fit model to data.
        [fitresult, gof] = fit( xData, yData, ft, opts );


